bhushan-asolkar/srca-ui

src/app/create-task/actions/contact-center/document/document.component.html, src/app/create-task/actions/contact-center/document/document.component.ts, src/app/create-task/create-task.module.ts, src/app/create-task/services/UploadFileService.service.ts
=> upload document changes

src/app/app.constants.ts, src/app/create-task/actions/contact-center/contact-center.component.html, src/app/create-task/actions/contact-center/contact-center.component.ts, src/app/create-task/actions/contact-center/task-detail/task-detail.component.html, src/app/create-task/actions/contact-center/task-detail/task-detail.component.scss, src/app/create-task/actions/contact-center/task-detail/task-detail.component.ts, src/app/create-task/services/create-task.service.ts, src/assets/scss/variables.scss
=> contact-center: task-details - added additional form fields and validations

src/app/create-task/actions/contact-center/contact-center.component.html
=> contact center edit changes

src/app/create-task/actions/contact-center/document/document.component.ts, src/assets/json/contact-center-edit.json
contact center edit documents changes
=> contact center edit documents changes

src/app/home/task/my-task-list/my-task-list.component.html
scroll bar added to my task list table
=> scroll bar added to my task list table

src/app/header/header.component.html, src/app/header/header.component.ts, src/app/home/dashboard/dashboard.component.ts
account type dropdown navigation
=> account type dropdown navigation

src/app/create-task/account/account-search/account-search.component.html, src/app/header/header.component.ts, src/app/home/dashboard/dashboard.component.html, src/app/home/home.module.ts, src/assets/scss/table.scss, src/styles.scss
account serach validation added
=> account serach validation added

src/app/home/dashboard/dashboard.component.ts, src/app/home/home.module.ts, src/app/home/task/my-task-list/my-task-list.component.ts
For home directory linting changes are added
=> Linting changes for home directory added

src/app/create-task/account/account-search/account-search.component.html, src/app/header/header.component.ts, src/app/home/task/my-task-list/my-task-list.component.html
my task list header UI changes
=> my task list header UI changes

src/app/create-task/account/account-search/account-search.component.html
account search validations added
=> account search validations added

src/app/create-task/account/account-search/account-search.component.html, src/app/create-task/account/account-search/account-search.component.scss, src/app/create-task/account/account-search/account-search.component.ts, src/app/create-task/account/account-summary/account-details/account-details.component.html, src/app/create-task/account/account.module.ts, src/app/create-task/actions/contact-center/contact-center.component.scss, src/app/create-task/services/create-task.service.ts, src/assets/scss/common.scss, src/assets/scss/panel.scss
account search validations and account table changes
=> account search validations and account table changes

src/app/create-task/account/account-search/account-search.component.spec.ts, src/app/create-task/actions/contact-center/task-detail/task-detail.component.ts
Linting changes are added for remaining files
=> Linting changes are added for remaining files

src/app/home/task/my-task-list/my-task-list.component.html, src/app/home/task/my-task-list/my-task-list.component.ts, src/assets/scss/table.scss
my task list resize,paginator,reorder added
=> my task list resize,paginator,reorder added

src/app/create-task/account/account-search/account-search.component.ts, src/app/create-task/actions/contact-center/contact-center.component.html, src/app/create-task/actions/contact-center/contact-center.component.scss, src/app/create-task/actions/contact-center/contact-center.component.ts, src/app/create-task/actions/contact-center/task-detail/task-detail.component.html, src/app/create-task/actions/contact-center/task-detail/task-detail.component.ts, src/app/create-task/services/create-task.service.ts
-save and cancel button changes added in contact center page
-linting changes for two other files are also resolved
=> save and cancel button changes added in contact center page

src/app/create-task/account/account-search/account-search.component.html, src/app/home/task/my-task-list/my-task-list.component.html, src/app/home/task/my-task-list/my-task-list.component.scss
=> paginator alignment

src/app/create-task/actions/contact-center/contact-center.component.html, src/app/create-task/actions/contact-center/task-detail/task-detail.component.html, src/app/create-task/actions/contact-center/task-detail/task-detail.component.ts
next button review details added
=> next button review details added

src/app/alert/alert.component.ts, src/app/create-task/account/account-summary/account-summary.component.html, src/app/create-task/actions/contact-center/document/document.component.html, src/app/create-task/actions/contact-center/task-detail/task-detail.component.html, src/app/home/task/my-task-list/my-task-list.component.html, src/app/home/task/my-task-list/my-task-list.component.scss, src/assets/scss/panel.scss, src/assets/scss/table.scss
=> my-task list table UI changes

src/app/create-task/actions/contact-center/contact-center.component.ts, src/app/create-task/actions/contact-center/task-detail/task-detail.component.html, src/app/create-task/actions/contact-center/task-detail/task-detail.component.ts
Officer list table added on review page
=> Officer list table added on review page

src/app/create-task/actions/contact-center/contact-center.component.html, src/app/create-task/actions/contact-center/contact-center.component.scss, src/app/create-task/actions/contact-center/document/document.component.html, src/app/home/task/my-task-list/my-task-list.component.scss
=> task list paginator changes

src/app/create-task/actions/contact-center/document/document.component.html, src/app/create-task/actions/contact-center/document/document.component.scss, src/app/create-task/actions/contact-center/document/document.component.ts, src/app/home/task/my-task-list/my-task-list.component.scss, src/assets/scss/common.scss
upload document validations added
=> upload document validations added

src/app/home/task/my-task-list/my-task-list.component.html, src/app/home/task/task.component.html, src/assets/scss/dropdowns.scss, src/assets/scss/table.scss
paginator alignment and table width UI changes
=> paginator alignment and table width UI changes

src/app/header/header.component.html, src/app/home/task/my-task-list/my-task-list.component.html, src/app/home/task/my-task-list/my-task-list.component.scss
login option removed from login screen
=> login option removed from login screen

src/app/create-task/account/account-summary/account-summary.component.spec.ts
Unit Test cases are added for account summary tab
=> Unit Test cases are added for account summary tab

src/app/create-task/account/account-summary/account-summary.component.html, src/app/create-task/account/account-summary/account-summary.component.scss, src/app/create-task/account/account-summary/account-summary.component.ts, src/app/tasks/components/contact-center-task/contact-center-task.component.html
Contact Center - Hide Add button in review and view screen
Added action column to account summary tasks table
=> contact center add button and account summary action column changes

src/app/app.constants.ts, src/app/tasks/components/communication/communication.component.html, src/app/tasks/components/communication/communication.component.scss, src/app/tasks/components/communication/communication.component.spec.ts, src/app/tasks/components/communication/communication.component.ts, src/app/tasks/task-container/task-container.component.html, src/app/tasks/tasks.module.ts, src/assets/scss/panel.scss
=> communication component added

src/app/tasks/components/communication/communication.component.html, src/app/tasks/components/communication/communication.component.scss, src/app/tasks/components/communication/communication.component.ts
communication component validations added
=> communication component validations added

src/app/tasks/components/document/document.component.html, src/app/tasks/components/document/document.component.ts
delete and preview icons added in documents table
=> delete and preview icons added in documents table

src/app/tasks/components/audit/audit.component.html, src/app/tasks/components/audit/audit.component.scss, src/app/tasks/components/audit/audit.component.spec.ts, src/app/tasks/components/audit/audit.component.ts, src/app/tasks/task-container/task-container.component.html, src/app/tasks/tasks.module.ts
=> audit tab changes are added

src/app/app.constants.ts, src/app/tasks/components/audit/audit.component.html, src/app/tasks/components/audit/audit.component.scss, src/app/tasks/components/audit/audit.component.ts, src/app/tasks/tasks.module.ts
multiselect tab is added for filters
=> multiselect tab is added for filters

src/app/tasks/components/communication/communication.component.html, src/app/tasks/components/communication/communication.component.scss, src/app/tasks/components/communication/communication.component.ts, src/assets/scss/common.scss, src/assets/scss/dropdowns.scss, src/assets/scss/panel.scss
communication details table added
=> communication details table added

src/app/tasks/components/audit/audit.component.html, src/app/tasks/components/audit/audit.component.scss, src/app/tasks/components/audit/audit.component.ts, src/app/tasks/model/audit.ts, src/app/tasks/tasks.module.ts
Add note button changes added with popup box
=> Add note button changes added with popup box

src/app/tasks/components/audit/audit.component.html
audit type css issue resolve for filter
=> audit type css issue resolve for filter

src/app/tasks/components/account-maintenance-task/account-maintenance-task.component.html, src/app/tasks/components/account-maintenance-task/account-maintenance-task.component.scss, src/app/tasks/components/account-maintenance-task/account-maintenance-task.component.ts, src/app/tasks/services/tasks.service.ts, src/assets/scss/common.scss
account maintenance UI changes
=> account maintenance UI changes

src/app/tasks/components/account-maintenance-task/account-maintenance-task.component.html, src/app/tasks/components/account-maintenance-task/account-maintenance-task.component.ts
account maintainance UI changes
=> account maintainance UI changes

src/app/tasks/components/audit/audit.component.html, src/app/tasks/components/audit/audit.component.scss
scroll and sorting changes are added
=> scroll and sorting changes are added

src/app/tasks/components/audit/audit.component.html, src/app/tasks/components/audit/audit.component.scss
=> audit scroll UI changes
